version: 2.1

jobs:
  build-1:
    docker:
      - image: cimg/base:current
    steps:
      - checkout  # リポジトリからコードをチェックアウト
      - run: echo "tessshhhhhhhsssttttt"
      - run: echo "aaaaaaaaaaaaaaaaaaaa"

workflows:
  version: 2
  build-job:
    when:
      not:
        and:
          - equal: [ "webhook", << pipeline.trigger_source >> ]
          - matches:
            pattern: "^dependabot.*$"
            value: << pipeline.git.branch >>
    jobs:
      - build-1
